version: '2'

services:
  web:
    build: .
    image: michael_darden
    command: python /code/manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
      - ~/.aws:/root/.aws:ro
    ports:
      - 8001:8002
